# Generated by Django 5.2.17 on 2026-09-30 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_existing_users_are_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('progress', 'Serie registrata'), ('completed', 'Sfida completata')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_prob', models.FloatField()),
                ('delivered', models.BooleanField()),
                ('devices', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='challenge.pushupentry')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='challenge_n_recipie_20439e_idx')],
            },
        ),
    ]
