# Generated by Django 5.2.17 on 2026-09-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_notification_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGoalChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_changes', to='challenge.group')),
            ],
            options={
                'ordering': ['group', 'effective_from'],
                'constraints': [models.UniqueConstraint(fields=('group', 'effective_from'), name='unique_group_goal_per_day')],
            },
        ),
    ]
